### ISSUE TITLE
pass bitscheme

### ISSUE THREAD

**Issue by drernie** [TheSwanFactory/hclang#195]
npm run bs

```
$-.test-fail ““`Hello`` World`” ?“`Hello World`” !““Hello World”””;“{"total":7,"pass":6,"fail":1}”;
$-.test-fail ““the-answer” ?“42” !“$!.name-missing “$:HCTest.113.the-answer”;””;“{"total":8,"pass":6,"fail":2}”;
$-.test-fail ““ther-answer” ?“$ther-answer” !“$!.name-missing “$:HCTest.113.ther-answer”;””;“{"total":9,"pass":6,"fail":3}”;
```

**Comment by drernie** [comment]
```
file:///Users/ernest/Documents/GitHub/hclang/lib/src/frames/frame-alias.js:34
            const here = context.get_here(key);
                                 ^

TypeError: Cannot read properties of undefined (reading 'get_here')
    at FrameAlias.find (file:///Users/ernest/Documents/GitHub/hclang/lib/src/frames/frame-alias.js:34:34)
    at FrameAlias.in (file:///Users/ernest/Documents/GitHub/hclang/lib/src/frames/frame-alias.js:14:30)
    at file:///Users/ernest/Documents/GitHub/hclang/lib/src/frames/frame-expr.js:14:34
    at Array.reduce (<anonymous>)
    at FrameExpr.in (file:///Users/ernest/Documents/GitHub/hclang/lib/src/frames/frame-expr.js:13:34)
    at file:///Users/ernest/Documents/GitHub/hclang/lib/src/frames/frame-expr.js:14:34
    at Array.reduce (<anonymous>)
    at FrameBind.in (file:///Users/ernest/Documents/GitHub/hclang/lib/src/frames/frame-expr.js:13:34)
    at file:///Users/ernest/Documents/GitHub/hclang/lib/src/frames/frame-expr.js:14:34
    at Array.reduce (<anonymous>)
```
